# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install --production --ignore-scripts

# Copy the rest of the files
COPY . .

# Build the project
RUN npm run build

# Expose port if necessary (not needed for stdio based MCP)

CMD ["node", "build/index.js"]
